/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  Todo,
} from './todo';

import {
  TodoList as TodoList
} from './components/todo-list/todo-list';

declare global {
  interface HTMLTodoListElement extends TodoList, HTMLElement {
  }
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  interface ElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-list": JSXElements.TodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListAttributes extends HTMLAttributes {
      allCompleted?: boolean;
      todos?: Todo[];
    }
  }
}


import {
  TodoMvc as TodoMvc
} from './components/todo-mvc/todo-mvc';

declare global {
  interface HTMLTodoMvcElement extends TodoMvc, HTMLElement {
  }
  var HTMLTodoMvcElement: {
    prototype: HTMLTodoMvcElement;
    new (): HTMLTodoMvcElement;
  };
  interface HTMLElementTagNameMap {
    "todo-mvc": HTMLTodoMvcElement;
  }
  interface ElementTagNameMap {
    "todo-mvc": HTMLTodoMvcElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-mvc": JSXElements.TodoMvcAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoMvcAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  TodoView as TodoView
} from './components/todo-view/todo-view';

declare global {
  interface HTMLTodoViewElement extends TodoView, HTMLElement {
  }
  var HTMLTodoViewElement: {
    prototype: HTMLTodoViewElement;
    new (): HTMLTodoViewElement;
  };
  interface HTMLElementTagNameMap {
    "todo-view": HTMLTodoViewElement;
  }
  interface ElementTagNameMap {
    "todo-view": HTMLTodoViewElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-view": JSXElements.TodoViewAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoViewAttributes extends HTMLAttributes {
      todo?: Todo;
    }
  }
}

